GAME_WIDTH: int = 640
GAME_HEIGHT: int = 480

PARTICLE_TILES: int = 3
GAME_SUDDEN_DEATH_TIME: int = 60000

PLAYER_WIDTH: int = 30
PLAYER_HEIGHT: int = 30
PLAYER_DECREASE_Y: float = 0.0005
PLAYER_HIT_BLOCK_VEC_Y: float = -0.4
PLAYER_HIT_BLOCK_DIFFERENCE_VEC_Y: float = 0.003
PLAYER_HIT_PLAYER_VEC_Y: float = -0.25
PLAYER_HIT_BIRD_VEC_Y: float = -0.3
PLAYER_MAX_VEC_X: float = 0.16
PLAYER_MAX_VEC_Y: float = 0.4
PLAYER_ACCELERATION_X: float = 0.0027
PLAYER_DECREASE_X: float = 0.0027
PLAYER_MAX_VEC_X_OVER_ENEMY: float = 0.13

PLAYER_FIRE_TILES: int = 4
PLAYER_FIRE_TIME: int = 150

ICEBLOCK_WIDTH: int = 30
ICEBLOCK_HEIGHT: int = 30
ICEBLOCK_HITS: int = 3
ICEBLOCK_DECREASE_VEC_X: float = 0.4 / 1000
ICEBLOCK_HIT_VEC_X: float = 6.5 / 1000

CHANGE_MENU_TO_GAME: float = 0.3
WATER_HEIGHT: int = 70

FISH_TILES: int = 8
FISH_TIME: int = 150

BIRD_TILES: int = 4
BIRD_TIME: int = 150
BIRD_DECREASE_Y: float = 0.00035

ABOVE_PIXEL: int = 5
BUTTON_MAX_CHANGE_Y: int = 3
WAVE_MAX_CHANGE_Y: int = 3
ICEBLOCK_MAX_CHANGE_Y: int = 4

PLAYER_ONE: int = 0
PLAYER_TWO: int = 1

AI_HUMAN: int = 0
AI_JOJO: int = 1
AI_TRAZZAG: int = 2
AI_EASY: int = 3
AI_MIDDLE: int = 4
AI_HARD: int = 5
AI_AI: int =1

GOODIE_WIDTH: int = 40
GOODIE_HEIGHT: int = 45
GOODIE_FIRE: int = 0
GOODIE_ICE_LITTLE: int = 1
GOODIE_ICE_BIG: int = 2
GOODIE_SLOWER: int = 3
GOODIE_HIGHER: int = 4
GOODIE_FASTER: int = 5